# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 2

install:
  - npm install

build: off

build_script:
  - npm run dist
  - ls dist

artifacts:
  - path: dist\*.exe
    name: win-installer

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: win-installer
    draft: false
    prerelease: false

    auth_token:
        secure: 7YTszSdWqyY7R0mhVI409ou4i1giTS8XH4kwjxUCSOTYboqCIVu3SMFdIr33X2ep
    on:
      branch: master                # release from master branch only
