# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 2

install:
  - npm install

build: off

build_script:
  - npm run dist
  - ls dist

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: "dist/*.exe"           # upload all NuGet packages to release assets
    draft: false
    prerelease: false

    auth_token:
        secure: 7YTszSdWqyY7R0mhVI409ou4i1giTS8XH4kwjxUCSOTYboqCIVu3SMFdIr33X2ep
    on:
      branch: master                # release from master branch only
